# Generated by Django 4.2.9 on 2026-02-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('approver', 'Approver'), ('viewer', 'Viewer')], max_length=50, unique=True)),
                ('can_create_product', models.BooleanField(default=False)),
                ('can_edit_product', models.BooleanField(default=False)),
                ('can_approve_product', models.BooleanField(default=False)),
                ('can_delete_product', models.BooleanField(default=False)),
            ],
        ),
    ]
